version: '2'

services:
  jira:
    image: asos/jira
    hostname: jira
    volumes:
      - /data/atlassian/jira:/var/atlassian/jira
    ports:
      - '8080:8080'
    environment:
      - 'CATALINA_OPTS= -Xms256m -Xmx1g'
      - 'JIRA_PROXY_NAME='
      - 'JIRA_PROXY_PORT='
      - 'JIRA_PROXY_SCHEME='
      - 'JIRA_DELAYED_START=10'
    external_links:
      - database/mysql
    labels:
      com.asos.description: "Atlassian Jira"
      com.asos.service: "jira"
      io.rancher.scheduler.affinity:host_label: host=atlassian
      io.rancher.container.pull_image: always
